Hotfix getsortedranking예외처리
Team-MTG/BackEnd pull request #66
Opened 2023-01-19 07:00 UTC by Icln

프론트에서 0 이하의 값을 넘겨줬을 때를 예외처리 했습니다

2023-01-19 11:18 UTC, jiione approved these changes
LGTM

2023-01-19 16:27 UTC, kwYoohae requested changes
현재 API 문서가 잘못되어 Ranking중 POST method에서의 dto를 수정하는바람에 테스트 코드가 전체적으로 돌아가지 않는 현상을 보이고 있습니다. 

그 부분먼저 hotfix하고 올려야할것 같습니다. 

또한 저도 까먹어서 이런 사단이 났지만, Pull Request 올리기전에 `./gradlew clean test` 를 한번 하면 오류 파악이 쉬울것 같습니다. 

혹은, github action으로 해당 항목 자동으로 test를 돌려 conflict가 안나는지 확인하게 하도록 하겠습니다 죄송합니다😭

2023-01-20 05:28 UTC, Icln commented
@kwYoohae 파일 수정해서 올렸습니다~

2023-01-20 05:45 UTC, kwYoohae approved these changes

2023-01-20 05:46 UTC, merged